### ISSUE TITLE
Android 12: Crash after latest update

### ISSUE THREAD

**Issue by bashtian** [sal0max/muzei-nationalgeographic#14] opened 2022-01-05 08:31 UTC
Following Android 12 change leads to a crash in the current version of the plugin:
https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability

```
AndroidRuntime: java.lang.IllegalArgumentException: de.msal.muzei.nationalgeographic: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
AndroidRuntime: Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
```

**Comment by sal0max** [comment] 2022-01-05 12:03
Thanks a lot for the issue.
Can confirm. Caused by an old non-android library.

**Comment by sal0max** [comment] 2022-01-05 12:11
Fixed in 95f87df1c2aee6e8016fa89cd1a676a39de1a8fc

**Comment by sal0max** [comment] 2022-01-05 12:37
Update is now live in the Google Play Store.

**Comment by bashtian** [comment] 2022-01-06 20:49
Works again, thank you for the quick fix!

**Closed** 2022-01-06 20:49 UTC
